### ISSUE TITLE
pls support to 7.1*.

### ISSUE THREAD

**Issue by phoenix110** [pfurini/cuba-component-forgot-password#10]
**I'm submitting a feature request**

* **Component Version:**
3.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **CUBA Version:**
7.1.0

* **Java Version:**
Oracle JDK 1.8.0_144

**Current behavior:**
don't support to 7.1*.

**Expected/desired behavior:**

* support to 7.1*.

**Comment by pfurini** [comment]
The component has just been updated for CUBA 7.1, please see the relevant notes in the README.

You need to wait for the official marketplace to pick up the updated version (4.0.0), or enter the new coordinates in your `build.gradle` file if you're in a hurry.
