### ISSUE TITLE
RootView exception... platform 7.0.6

### ISSUE THREAD

**Issue by selimabatay** [pfurini/cuba-component-forgot-password#7]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Component Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **CUBA Version:**
6.6.4

* **Java Version:**
Oracle JDK 1.8.0_144

**Current behavior:**

**Expected/desired behavior:**

* **What is the motivation / use case for changing the behavior?**

**Comment by selimabatay** [comment]
hi. we use platform 7.0.6 but "linkContext.getApp().getTopLevelWindow()" type is "RootView" not Window.TopLevelWindow. please fix it issue. thanks

**Comment by selimabatay** [comment]
RootWindow topLevelWindow = linkContext.getApp().getTopLevelWindow();
                    ExtAppLoginWindow loginWindow = (ExtAppLoginWindow) linkContext.getApp().getTopLevelWindow();
                    if (loginWindow != null) {
                        loginWindow.showChangePasswordDialog(token);
                    }

Exception:

ClassCastException: com.haulmont.cuba.web.gui.WebRootWindow cannot be cast to com.innosoft.dap.web.security.ExtAppLoginWindow

**Comment by pfurini** [comment]
This component is not yet ready for platform version 7.x, so errors are expected.
The versions it supports are clearly indicated in the README file.

I plan to migrate this component, and the [cuba-component-user-profile](https://github.com/pfurini/cuba-component-user-profile), in the following days.

**Comment by pfurini** [comment]
The component now supports CUBA 7.0
